-- trade_decisions (migrations/0001_init.sql, extended by
-- 0007_trade_decisions_portfolio.sql) persists thesis/risk_decision/
-- portfolio_decision, but none of the LLM reasoning that actually produced
-- them: the per-article analyst opinions (news_event/sentiment/technical)
-- and the bull/bear debate + judge verdict were only ever kept in
-- graph/pipeline.js's in-memory state / the opaque pipeline_checkpoints
-- JSON blob -- never a queryable column on the decision itself. This was
-- flagged explicitly in src/dashboard.js's own module header (item 4):
-- "Bull/bear debate reasoning isn't shown -- not persisted anywhere yet."
--
-- Adding two columns here rather than overloading thesis/risk_decision,
-- matching this project's existing convention of a migration per new
-- JSON-blob column (see 0007's own header). This project's pre-existing
-- analyst_opinions/debates tables (migrations/0001_init.sql) are a more
-- normalized home for the same data, but ALSO have no write path yet and
-- would require an id/news_item_id join per dashboard row to read back --
-- deliberately not wired up in this change; storing the two blobs directly
-- on trade_decisions keeps the dashboard read to the single row it already
-- fetches, matching how thesis/risk_decision/portfolio_decision already
-- work on this same table. Fully wiring analyst_opinions/debates remains a
-- separate, larger normalization that plan.md can track if ever needed.
ALTER TABLE trade_decisions ADD COLUMN opinions TEXT; -- JSON array of AnalystOpinion (news_event/sentiment/technical -- technical may be absent when no price history existed yet)
ALTER TABLE trade_decisions ADD COLUMN debate TEXT;   -- JSON DebateVerdict (bull, bear nested inside, plus direction/confidence/timeHorizon/justification)
