-- Adds exit_price to positions: the last piece needed to compute a
-- realized return for a closed position (plan.md open item -- see
-- migrations/0006's header, which added direction/entry_price/etc but left
-- closePosition with no way to record what price a position actually
-- closed at, so realized P&L could never be computed even once exit logic
-- existed). storage/d1.js#closePosition now accepts and persists it;
-- src/graph/settle.js#settlePositionOutcome is the new caller that turns
-- entry_price + exit_price into a realized return and feeds it into the
-- reflection/memory loop (src/graph/reflection.js#closeTheLoop, which
-- existed already but had no caller until this change -- see plan.md).
--
-- Nullable ON PURPOSE, same convention as entry_price (migrations/0006):
-- a time_based exit with no price_bars data for that ticker/date still
-- closes the position (evaluateExit's null-price handling), just without a
-- computable realized return -- an honest gap, not a fabricated price.
ALTER TABLE positions ADD COLUMN exit_price REAL;
